### ISSUE TITLE
Token indices for Extractions

### ISSUE THREAD

**Issue by RobertWardenga** [gkiril/benchie#3]
Hi, 
from the AnnIE tool it is possible to also obtain the token indices of the extractions. Is there a version of the gold datasets in which the token indices are preserved?

**Comment by gkiril** [comment]
Hi @RobertWardenga , appologies for the late reply. Unfortunatelly, such version does not exist. I think you can easily change this by manipulating the AnnIE tool which is open sourced as well. Hope this helps :)
