### ISSUE TITLE
BenchIE-E/C/M

### ISSUE THREAD

**Issue by filip-cermak** [gkiril/benchie#4]
Thank you for this work. Is there any chance that the code for the BenchIE-E/C/M is also available? I am trying to run this benchmark comprehensively on Deepex and GPT3.5 (used as open IE).

Thank you.

**Comment by gkiril** [comment]
Hi @filip-cermak , sorry for the late reply. Yes, BenchIE-E/C/M is also available here: https://aclanthology.org/attachments/2022.acl-long.307.software.zip 

You can also find the notebook with experiments.
